// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewBooking = `-- name: CreateNewBooking :one
INSERT INTO bookings (amount, user_id, booking_platform, free_cancel_before, booking_start, booking_end, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, amount, user_id, booking_platform, free_cancel_before, booking_start, booking_end, description, created_at, updated_at, deleted_at
`

type CreateNewBookingParams struct {
	Amount           pgtype.Numeric   `json:"amount"`
	UserID           int32            `json:"user_id"`
	BookingPlatform  string           `json:"booking_platform"`
	FreeCancelBefore pgtype.Timestamp `json:"free_cancel_before"`
	BookingStart     pgtype.Timestamp `json:"booking_start"`
	BookingEnd       pgtype.Timestamp `json:"booking_end"`
	Description      string           `json:"description"`
}

func (q *Queries) CreateNewBooking(ctx context.Context, arg CreateNewBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createNewBooking,
		arg.Amount,
		arg.UserID,
		arg.BookingPlatform,
		arg.FreeCancelBefore,
		arg.BookingStart,
		arg.BookingEnd,
		arg.Description,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.UserID,
		&i.BookingPlatform,
		&i.FreeCancelBefore,
		&i.BookingStart,
		&i.BookingEnd,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
