// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: households.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, address, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, name, address, created_at, updated_at
`

type CreateHouseholdParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.Address)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, name, address, created_at, updated_at FROM households
WHERE id = $1
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id int32) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByName = `-- name: GetHouseholdByName :one
SELECT id, name, address, created_at, updated_at FROM households
WHERE name = $1
`

func (q *Queries) GetHouseholdByName(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByName, name)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
