// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewUser = `-- name: CreateNewUser :one
INSERT INTO users (email, username, lastname, gender, role, household_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,  NOW(), NOW())
RETURNING id, email, username, lastname, gender, role, household_id, created_at, updated_at
`

type CreateNewUserParams struct {
	Email       string      `json:"email"`
	Username    string      `json:"username"`
	Lastname    string      `json:"lastname"`
	Gender      string      `json:"gender"`
	Role        string      `json:"role"`
	HouseholdID pgtype.Int4 `json:"household_id"`
}

func (q *Queries) CreateNewUser(ctx context.Context, arg CreateNewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createNewUser,
		arg.Email,
		arg.Username,
		arg.Lastname,
		arg.Gender,
		arg.Role,
		arg.HouseholdID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Lastname,
		&i.Gender,
		&i.Role,
		&i.HouseholdID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
