// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID          int32            `json:"id"`
	Amount      pgtype.Numeric   `json:"amount"`
	UserID      int32            `json:"user_id"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Household struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Address   pgtype.Text      `json:"address"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID          int32            `json:"id"`
	Email       string           `json:"email"`
	Username    string           `json:"username"`
	Lastname    string           `json:"lastname"`
	Gender      string           `json:"gender"`
	Role        string           `json:"role"`
	HouseholdID pgtype.Int4      `json:"household_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
