// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error)
	GetHouseholdByID(ctx context.Context, id int32) (Household, error)
	GetHouseholdByName(ctx context.Context, name string) (Household, error)
}

var _ Querier = (*Queries)(nil)
